/** Curated country list for the country selector (Nigeria first — primary market). */
export const COUNTRIES: string[] = [
  'Nigeria',
  'Ghana',
  'Kenya',
  'South Africa',
  'Egypt',
  'Morocco',
  'Tanzania',
  'Uganda',
  'Rwanda',
  'Ethiopia',
  'Cameroon',
  'Senegal',
  "Côte d'Ivoire",
  'Algeria',
  'Tunisia',
  'United States',
  'United Kingdom',
  'Canada',
  'Ireland',
  'Germany',
  'France',
  'Netherlands',
  'Spain',
  'Portugal',
  'Italy',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Switzerland',
  'Austria',
  'Belgium',
  'United Arab Emirates',
  'Saudi Arabia',
  'Qatar',
  'India',
  'Pakistan',
  'Bangladesh',
  'Philippines',
  'Indonesia',
  'Malaysia',
  'Singapore',
  'Vietnam',
  'China',
  'Japan',
  'South Korea',
  'Australia',
  'New Zealand',
  'Brazil',
  'Argentina',
  'Mexico',
  'Colombia',
  'Chile',
  'Turkey',
  'Other',
]
