/** Industry list for the business "Industry" selector. Searchable; "Other" last. */
export const INDUSTRIES: string[] = [
  'Software & IT',
  'Fintech',
  'E-commerce',
  'Artificial Intelligence',
  'Cybersecurity',
  'Telecommunications',
  'Gaming',
  'Internet & Web Services',
  'Marketing & Advertising',
  'Design & Creative',
  'Media & Entertainment',
  'Film & Video',
  'Music',
  'Photography',
  'Publishing',
  'Fashion & Apparel',
  'Beauty & Personal Care',
  'Arts & Crafts',
  'Architecture',
  'Engineering',
  'Construction',
  'Real Estate',
  'Manufacturing',
  'Automotive',
  'Aerospace & Defense',
  'Energy & Utilities',
  'Oil & Gas',
  'Mining',
  'Agriculture',
  'Food & Beverage',
  'Hospitality & Tourism',
  'Travel',
  'Events',
  'Sports & Fitness',
  'Retail',
  'Consumer Goods',
  'Logistics & Transportation',
  'Supply Chain',
  'Healthcare',
  'Pharmaceuticals',
  'Biotechnology',
  'Wellness',
  'Education',
  'E-learning',
  'Finance & Banking',
  'Insurance',
  'Investment & Venture Capital',
  'Accounting',
  'Legal Services',
  'Consulting',
  'Human Resources & Recruiting',
  'Customer Support',
  'Nonprofit & NGO',
  'Government & Public Sector',
  'Environmental Services',
  'Security',
  'Telehealth',
  'Blockchain & Crypto',
  'Other',
]
