/**
 * Nigerian tertiary institutions — universities (federal, state, private) and
 * polytechnics — for the onboarding "University / institution" selector.
 * Searchable; an "Other (not listed)" fallback sits at the end.
 */
export const NIGERIAN_INSTITUTIONS: string[] = [
  // ── Federal Universities ───────────────────────────────────────────────────
  'University of Ibadan',
  'University of Lagos',
  'University of Nigeria, Nsukka',
  'Ahmadu Bello University, Zaria',
  'Obafemi Awolowo University, Ile-Ife',
  'University of Benin',
  'University of Ilorin',
  'University of Jos',
  'University of Calabar',
  'University of Maiduguri',
  'University of Port Harcourt',
  'University of Uyo',
  'University of Abuja',
  'Bayero University, Kano',
  'Usmanu Danfodiyo University, Sokoto',
  'Nnamdi Azikiwe University, Awka',
  'Federal University of Technology, Akure (FUTA)',
  'Federal University of Technology, Minna (FUTMINNA)',
  'Federal University of Technology, Owerri (FUTO)',
  'Modibbo Adama University, Yola',
  'Federal University of Agriculture, Abeokuta (FUNAAB)',
  'Michael Okpara University of Agriculture, Umudike',
  'Joseph Sarwuan Tarka University, Makurdi',
  'Nigerian Defence Academy, Kaduna',
  'National Open University of Nigeria (NOUN)',
  'Federal University of Petroleum Resources, Effurun',
  'Federal University, Oye-Ekiti (FUOYE)',
  'Federal University, Dutse',
  'Federal University, Lafia',
  'Federal University, Lokoja',
  'Federal University, Kashere',
  'Federal University, Wukari',
  'Federal University, Dutsin-Ma',
  'Federal University, Otuoke',
  'Federal University, Gashua',
  'Federal University, Birnin Kebbi',
  'Federal University, Gusau',
  'Alex Ekwueme Federal University, Ndufu-Alike',
  'Nigeria Maritime University, Okerenkoko',
  'Nigerian Army University, Biu',
  'Air Force Institute of Technology, Kaduna',
  'Federal University of Health Sciences, Otukpo',
  'Federal University of Health Sciences, Azare',
  'Federal University of Health Sciences, Ila Orangun',
  'David Umahi Federal University of Medical Sciences, Uburu',

  // ── State Universities ──────────────────────────────────────────────────────
  'Lagos State University (LASU)',
  'Lagos State University of Science and Technology, Ikorodu',
  'Rivers State University',
  'Ladoke Akintola University of Technology (LAUTECH), Ogbomoso',
  'Ekiti State University (EKSU)',
  'Olabisi Onabanjo University, Ago-Iwoye',
  'Ambrose Alli University, Ekpoma',
  'Delta State University, Abraka',
  'Enugu State University of Science and Technology (ESUT)',
  'Imo State University, Owerri',
  'Abia State University, Uturu',
  'Ebonyi State University, Abakaliki',
  'Chukwuemeka Odumegwu Ojukwu University, Uli',
  'Benue State University, Makurdi',
  'Kogi State University (Prince Abubakar Audu University), Anyigba',
  'Nasarawa State University, Keffi',
  'Kaduna State University',
  'Kano University of Science and Technology, Wudil',
  'Gombe State University',
  'Adamawa State University, Mubi',
  'Taraba State University, Jalingo',
  'Plateau State University, Bokkos',
  'Bauchi State University, Gadau',
  'Yobe State University, Damaturu',
  'Borno State University, Maiduguri',
  'Sokoto State University',
  'Zamfara State University, Talata Mafara',
  'Kebbi State University of Science and Technology, Aliero',
  'Umaru Musa Yar’adua University, Katsina',
  'Ibrahim Badamasi Babangida University, Lapai',
  'Sule Lamido University, Kafin Hausa',
  'Niger Delta University, Wilberforce Island',
  'Akwa Ibom State University, Ikot Akpaden',
  'University of Cross River State, Calabar',
  'Adekunle Ajasin University, Akungba',
  'Olusegun Agagu University of Science and Technology, Okitipupa',
  'University of Medical Sciences, Ondo',
  'Osun State University (UNIOSUN)',
  'Tai Solarin University of Education, Ijagun',
  'Edo State University, Uzairue',
  'Bayelsa Medical University, Yenagoa',
  'Gombe State University of Science and Technology, Kumo',

  // ── Private Universities ────────────────────────────────────────────────────
  'Covenant University, Ota',
  'Babcock University, Ilishan-Remo',
  'Bowen University, Iwo',
  'Afe Babalola University, Ado-Ekiti (ABUAD)',
  'Landmark University, Omu-Aran',
  'Redeemer’s University, Ede',
  'Pan-Atlantic University, Lagos',
  'American University of Nigeria, Yola',
  'Bells University of Technology, Ota',
  'Lead City University, Ibadan',
  'Caleb University, Lagos',
  'Crawford University, Igbesa',
  'Madonna University, Okija',
  'Igbinedion University, Okada',
  'Benson Idahosa University, Benin City',
  'Ajayi Crowther University, Oyo',
  'Joseph Ayo Babalola University, Ikeji-Arakeji',
  'Achievers University, Owo',
  'Elizade University, Ilara-Mokin',
  'Adeleke University, Ede',
  'Wesley University, Ondo',
  'Summit University, Offa',
  'Al-Hikmah University, Ilorin',
  'Fountain University, Osogbo',
  'Crescent University, Abeokuta',
  'Mountain Top University, Ibafo',
  'Augustine University, Ilara-Epe',
  'Anchor University, Lagos',
  'Hallmark University, Ijebu-Itele',
  'Chrisland University, Abeokuta',
  'McPherson University, Seriki Sotayo',
  'Dominican University, Ibadan',
  'Kings University, Ode-Omu',
  'Southwestern University, Okun-Owa',
  'Atiba University, Oyo',
  'Precious Cornerstone University, Ibadan',
  'Trinity University, Lagos',
  'Westland University, Iwo',
  'Thomas Adewumi University, Oko',
  'Veritas University, Abuja',
  'Baze University, Abuja',
  'Nile University of Nigeria, Abuja',
  'Bingham University, Karu',
  'Philomath University, Abuja',
  'Salem University, Lokoja',
  'Kwararafa University, Wukari',
  'Renaissance University, Enugu',
  'Caritas University, Enugu',
  'Godfrey Okoye University, Enugu',
  'Coal City University, Enugu',
  'Gregory University, Uturu',
  'Rhema University, Aba',
  'Clifford University, Owerrinta',
  'Spiritan University, Nneochi',
  'Tansian University, Umunya',
  'Paul University, Awka',
  'Legacy University, Okija',
  'Hezekiah University, Umudi',
  'Evangel University, Akaeze',
  'PAMO University of Medical Sciences, Port Harcourt',
  'Eko University of Medical and Health Sciences, Ijanikin',
  'Edwin Clark University, Kiagbodo',
  'Michael and Cecilia Ibru University, Agbarha-Otor',
  'Admiralty University of Nigeria, Ibusa',
  'Western Delta University, Oghara',
  'Novena University, Ogume',
  'Wellspring University, Benin City',
  'Glorious Vision University, Ogwa',
  'Topfaith University, Mkpatak',
  'Skyline University Nigeria, Kano',
  'Khalifa Isiyaku Rabiu University, Kano',
  'Maryam Abacha American University of Nigeria, Kano',
  'Capital City University, Kano',
  'Al-Qalam University, Katsina',
  'Greenfield University, Kaduna',
  'PEN Resource University, Gombe',
  'NOK University, Kachia',
  'Mewar International University, Masaka',

  // ── Federal Polytechnics ───────────────────────────────────────────────────
  'Yaba College of Technology (YABATECH), Lagos',
  'Auchi Polytechnic, Auchi',
  'Federal Polytechnic, Nekede (Owerri)',
  'Federal Polytechnic, Ilaro',
  'Federal Polytechnic, Ado-Ekiti',
  'Federal Polytechnic, Oko',
  'Federal Polytechnic, Bida',
  'Federal Polytechnic, Idah',
  'Federal Polytechnic, Offa',
  'Federal Polytechnic, Bauchi',
  'Federal Polytechnic, Mubi',
  'Federal Polytechnic, Damaturu',
  'Federal Polytechnic, Nasarawa',
  'Federal Polytechnic, Kaura Namoda',
  'Federal Polytechnic, Ede',
  'Federal Polytechnic, Ile-Oluji',
  'Federal Polytechnic, Ukana',
  'Federal Polytechnic, Ekowe',
  'Federal Polytechnic, Kabo',
  'Federal Polytechnic, Daura',
  'Federal Polytechnic, Bali',
  'Federal Polytechnic, Ayede',
  'Federal Polytechnic, Wannune',
  'Federal Polytechnic, Kaltungo',
  'Federal Polytechnic, Nyak (Shendam)',
  'Federal Polytechnic, Ugep',
  'Federal Polytechnic, Orogun',
  'Waziri Umaru Federal Polytechnic, Birnin Kebbi',
  'Hussaini Adamu Federal Polytechnic, Kazaure',
  'Federal School of Surveying, Oyo',

  // ── State & Private Polytechnics ────────────────────────────────────────────
  'The Polytechnic, Ibadan',
  'Institute of Management and Technology (IMT), Enugu',
  'Moshood Abiola Polytechnic, Abeokuta',
  'Rufus Giwa Polytechnic, Owo',
  'Kwara State Polytechnic, Ilorin',
  'Osun State Polytechnic, Iree',
  'Osun State College of Technology, Esa-Oke',
  'Abia State Polytechnic, Aba',
  'Imo State Polytechnic, Umuagwo',
  'Delta State Polytechnic, Ozoro',
  'Delta State Polytechnic, Ogwashi-Uku',
  'Delta State Polytechnic, Otefe-Oghara',
  'Edo State Polytechnic, Usen',
  'Kenule Beeson Saro-Wiwa Polytechnic, Bori',
  'Captain Elechi Amadi Polytechnic, Port Harcourt',
  'Akwa Ibom State Polytechnic, Ikot Osurua',
  'Cross River Institute of Technology and Management, Ugep',
  'Benue State Polytechnic, Ugbokolo',
  'Nasarawa State Polytechnic, Lafia',
  'Plateau State Polytechnic, Barkin Ladi',
  'Kaduna Polytechnic',
  'Hassan Usman Katsina Polytechnic',
  'Kano State Polytechnic',
  'Jigawa State Polytechnic, Dutse',
  'Binyaminu Usman Polytechnic, Hadejia',
  'Ramat Polytechnic, Maiduguri',
  'Adamawa State Polytechnic, Yola',
  'Gombe State Polytechnic, Bajoga',
  'Taraba State Polytechnic, Suntai',
  'Abdu Gusau Polytechnic, Talata Mafara',
  'Niger State Polytechnic, Zungeru',
  'Kogi State Polytechnic, Lokoja',
  'Gateway ICT Polytechnic, Saapade',
  'D.S. Adegbenro ICT Polytechnic, Itori',
  'Bauchi State Polytechnic',
  'Sokoto State Polytechnic',
  'Kebbi State Polytechnic, Dakingari',
  'Crown Polytechnic, Ado-Ekiti',
  'Wolex Polytechnic, Iwo',
  'Ronik Polytechnic, Lagos',
  'Grace Polytechnic, Lagos',
  'Heritage Polytechnic, Eket',
  'Covenant Polytechnic, Aba',
  'Interlink Polytechnic, Ijebu-Jesa',

  // ── Fallback ────────────────────────────────────────────────────────────────
  'Other (not listed)',
]
